# Time of knockout in seconds
knockout-time: 60

# Amount of xp levels required to revive a player
revive-levels: 5

# When true: add slowness effect for the player carrying a knocked out player
slowness-for-carrier: true

# Slowness amplifier for the player carrying a knocked out player; Slowness level is equal to amplifier + 1
slowness-amplifier: 0

# When true: when carrying player is hit, drop the knocked out player
drop-when-hit: true

# If true knocked out player will die when the knockout time ends otherwise will be revived
death-on-end: true

# When true: player will have blindness effect when knocked out
knockout-blindness: true

# Message for the player when knocked out
knockout-message: '&cYou have been knocked out! Ask someone to revive you or use /die to die at once.'

# Title message for the player when knocked out
knockout-title: '&cKnockout'

# Hologram title above the player when knocked out
knockout-hologram: '&cKnockout'

# Message for not allowed actions when knocked out
not-allowed-message: "&cYou can't do that when knocked out!"

# Message for the player with not enough levels to revive
# Use variable %levels% to show the required levels
no-levels-message: "&cYou don't have enough levels (%levels%) to revive that player"

# Title message for the rescuer when reviving
rescuer-reviving-title: '&aReviving...'

# Title message for the rescued when reviving
rescued-reviving-title: '&aYou are being revived...'

# Successful revive message for the rescuer
# Use variable %player% to show the rescued player name
rescuer-revived-message: '&aYou revived %player%'

# Successful revive message for the rescued
# Use variable %player% to show the rescuer player name
rescued-revived-message: '&aYou have been revived by %player%'

# Message when the player uses /die command and is not knocked out
invalid-die-message: "&cYou can use this command only when knocked out!"

# Message when the player uses /drop command and is not carrying any knocked out player
invalid-drop-message: "&cYou are not carrying any knocked out player!"

# Message when the player uses /carry command and there is no knocked out player nearby
invalid-carry-message: "&cDidn't find any nearby knocked out player to carry!"

# Message when the player uses /carry command and is already carrying a knocked out player
already-carrying-message: "&cYou are already carrying a knocked out player!"

# Message when the player doesn't have permission to do something
no-permission-message: "&4You don't have permission to do that!"

# Aliases for the commands
aliases:
    carry:
        - podnies
        -
    drop:
        - zrzuc
        -
    die:
        - zgin