name: KnockoutPlugin
version: '${project.version}'
main: org.mynion.knockoutplugin.KnockoutPlugin
api-version: '1.21'
commands:
  carry:
    description: Carry a knocked out player
  drop:
    description: Drop a knocked out player
  die:
    description: Die at once when knocked out
